################################################################################
## Form generated from reading UI file 'design.ui'
##
## Created by: Qt User Interface Compiler version 6.8.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QLabel, QLineEdit, QMainWindow,
    QPushButton, QSizePolicy, QStatusBar, QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(666, 433)
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Preferred, QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        icon = QIcon()
        icon.addFile(u"res/icn.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.solveBtn = QPushButton(self.centralwidget)
        self.solveBtn.setObjectName(u"solveBtn")
        self.solveBtn.setGeometry(QRect(20, 230, 131, 51))
        self.label_39 = QLabel(self.centralwidget)
        self.label_39.setObjectName(u"label_39")
        self.label_39.setGeometry(QRect(130, 80, 21, 16))
        sizePolicy.setHeightForWidth(self.label_39.sizePolicy().hasHeightForWidth())
        self.label_39.setSizePolicy(sizePolicy)
        self.label_40 = QLabel(self.centralwidget)
        self.label_40.setObjectName(u"label_40")
        self.label_40.setGeometry(QRect(20, 80, 31, 20))
        sizePolicy.setHeightForWidth(self.label_40.sizePolicy().hasHeightForWidth())
        self.label_40.setSizePolicy(sizePolicy)
        self.lStText = QLineEdit(self.centralwidget)
        self.lStText.setObjectName(u"lStText")
        self.lStText.setGeometry(QRect(60, 110, 61, 21))
        sizePolicy1 = QSizePolicy(QSizePolicy.Policy.Preferred, QSizePolicy.Policy.Fixed)
        sizePolicy1.setHorizontalStretch(0)
        sizePolicy1.setVerticalStretch(0)
        sizePolicy1.setHeightForWidth(self.lStText.sizePolicy().hasHeightForWidth())
        self.lStText.setSizePolicy(sizePolicy1)
        self.label_41 = QLabel(self.centralwidget)
        self.label_41.setObjectName(u"label_41")
        self.label_41.setGeometry(QRect(130, 110, 21, 16))
        sizePolicy.setHeightForWidth(self.label_41.sizePolicy().hasHeightForWidth())
        self.label_41.setSizePolicy(sizePolicy)
        self.rVnText = QLineEdit(self.centralwidget)
        self.rVnText.setObjectName(u"rVnText")
        self.rVnText.setGeometry(QRect(60, 170, 61, 21))
        sizePolicy1.setHeightForWidth(self.rVnText.sizePolicy().hasHeightForWidth())
        self.rVnText.setSizePolicy(sizePolicy1)
        self.label_42 = QLabel(self.centralwidget)
        self.label_42.setObjectName(u"label_42")
        self.label_42.setGeometry(QRect(20, 140, 31, 20))
        sizePolicy.setHeightForWidth(self.label_42.sizePolicy().hasHeightForWidth())
        self.label_42.setSizePolicy(sizePolicy)
        self.label_43 = QLabel(self.centralwidget)
        self.label_43.setObjectName(u"label_43")
        self.label_43.setGeometry(QRect(20, 170, 31, 20))
        sizePolicy.setHeightForWidth(self.label_43.sizePolicy().hasHeightForWidth())
        self.label_43.setSizePolicy(sizePolicy)
        self.lOtTex = QLineEdit(self.centralwidget)
        self.lOtTex.setObjectName(u"lOtTex")
        self.lOtTex.setGeometry(QRect(60, 140, 61, 21))
        sizePolicy1.setHeightForWidth(self.lOtTex.sizePolicy().hasHeightForWidth())
        self.lOtTex.setSizePolicy(sizePolicy1)
        self.label_44 = QLabel(self.centralwidget)
        self.label_44.setObjectName(u"label_44")
        self.label_44.setGeometry(QRect(20, 110, 31, 20))
        sizePolicy.setHeightForWidth(self.label_44.sizePolicy().hasHeightForWidth())
        self.label_44.setSizePolicy(sizePolicy)
        self.tText = QLineEdit(self.centralwidget)
        self.tText.setObjectName(u"tText")
        self.tText.setGeometry(QRect(60, 80, 61, 21))
        sizePolicy1.setHeightForWidth(self.tText.sizePolicy().hasHeightForWidth())
        self.tText.setSizePolicy(sizePolicy1)
        self.label_45 = QLabel(self.centralwidget)
        self.label_45.setObjectName(u"label_45")
        self.label_45.setGeometry(QRect(130, 140, 21, 16))
        sizePolicy.setHeightForWidth(self.label_45.sizePolicy().hasHeightForWidth())
        self.label_45.setSizePolicy(sizePolicy)
        self.label_46 = QLabel(self.centralwidget)
        self.label_46.setObjectName(u"label_46")
        self.label_46.setGeometry(QRect(130, 170, 21, 16))
        sizePolicy.setHeightForWidth(self.label_46.sizePolicy().hasHeightForWidth())
        self.label_46.setSizePolicy(sizePolicy)
        self.jXText = QLineEdit(self.centralwidget)
        self.jXText.setObjectName(u"jXText")
        self.jXText.setGeometry(QRect(550, 160, 61, 21))
        sizePolicy1.setHeightForWidth(self.jXText.sizePolicy().hasHeightForWidth())
        self.jXText.setSizePolicy(sizePolicy1)
        self.jXText.setReadOnly(True)
        self.label_47 = QLabel(self.centralwidget)
        self.label_47.setObjectName(u"label_47")
        self.label_47.setGeometry(QRect(518, 240, 31, 20))
        sizePolicy.setHeightForWidth(self.label_47.sizePolicy().hasHeightForWidth())
        self.label_47.setSizePolicy(sizePolicy)
        self.label_48 = QLabel(self.centralwidget)
        self.label_48.setObjectName(u"label_48")
        self.label_48.setGeometry(QRect(618, 80, 49, 16))
        sizePolicy.setHeightForWidth(self.label_48.sizePolicy().hasHeightForWidth())
        self.label_48.setSizePolicy(sizePolicy)
        self.label_49 = QLabel(self.centralwidget)
        self.label_49.setObjectName(u"label_49")
        self.label_49.setGeometry(QRect(618, 280, 49, 16))
        sizePolicy.setHeightForWidth(self.label_49.sizePolicy().hasHeightForWidth())
        self.label_49.setSizePolicy(sizePolicy)
        self.rOsText = QLineEdit(self.centralwidget)
        self.rOsText.setObjectName(u"rOsText")
        self.rOsText.setGeometry(QRect(550, 40, 61, 21))
        sizePolicy1.setHeightForWidth(self.rOsText.sizePolicy().hasHeightForWidth())
        self.rOsText.setSizePolicy(sizePolicy1)
        self.rOsText.setReadOnly(True)
        self.label_50 = QLabel(self.centralwidget)
        self.label_50.setObjectName(u"label_50")
        self.label_50.setGeometry(QRect(518, 100, 31, 20))
        sizePolicy.setHeightForWidth(self.label_50.sizePolicy().hasHeightForWidth())
        self.label_50.setSizePolicy(sizePolicy)
        self.xCText = QLineEdit(self.centralwidget)
        self.xCText.setObjectName(u"xCText")
        self.xCText.setGeometry(QRect(550, 120, 61, 21))
        sizePolicy1.setHeightForWidth(self.xCText.sizePolicy().hasHeightForWidth())
        self.xCText.setSizePolicy(sizePolicy1)
        self.xCText.setReadOnly(True)
        self.label_51 = QLabel(self.centralwidget)
        self.label_51.setObjectName(u"label_51")
        self.label_51.setGeometry(QRect(618, 200, 49, 16))
        sizePolicy.setHeightForWidth(self.label_51.sizePolicy().hasHeightForWidth())
        self.label_51.setSizePolicy(sizePolicy)
        self.label_52 = QLabel(self.centralwidget)
        self.label_52.setObjectName(u"label_52")
        self.label_52.setGeometry(QRect(518, 160, 31, 20))
        sizePolicy.setHeightForWidth(self.label_52.sizePolicy().hasHeightForWidth())
        self.label_52.setSizePolicy(sizePolicy)
        self.label_53 = QLabel(self.centralwidget)
        self.label_53.setObjectName(u"label_53")
        self.label_53.setGeometry(QRect(618, 320, 49, 16))
        sizePolicy.setHeightForWidth(self.label_53.sizePolicy().hasHeightForWidth())
        self.label_53.setSizePolicy(sizePolicy)
        self.label_54 = QLabel(self.centralwidget)
        self.label_54.setObjectName(u"label_54")
        self.label_54.setGeometry(QRect(518, 280, 31, 20))
        sizePolicy.setHeightForWidth(self.label_54.sizePolicy().hasHeightForWidth())
        self.label_54.setSizePolicy(sizePolicy)
        self.label_55 = QLabel(self.centralwidget)
        self.label_55.setObjectName(u"label_55")
        self.label_55.setGeometry(QRect(518, 40, 31, 20))
        sizePolicy.setHeightForWidth(self.label_55.sizePolicy().hasHeightForWidth())
        self.label_55.setSizePolicy(sizePolicy)
        self.aText = QLineEdit(self.centralwidget)
        self.aText.setObjectName(u"aText")
        self.aText.setGeometry(QRect(550, 60, 61, 21))
        sizePolicy1.setHeightForWidth(self.aText.sizePolicy().hasHeightForWidth())
        self.aText.setSizePolicy(sizePolicy1)
        self.aText.setReadOnly(True)
        self.label_56 = QLabel(self.centralwidget)
        self.label_56.setObjectName(u"label_56")
        self.label_56.setGeometry(QRect(618, 100, 49, 16))
        sizePolicy.setHeightForWidth(self.label_56.sizePolicy().hasHeightForWidth())
        self.label_56.setSizePolicy(sizePolicy)
        self.label_57 = QLabel(self.centralwidget)
        self.label_57.setObjectName(u"label_57")
        self.label_57.setGeometry(QRect(518, 300, 31, 20))
        sizePolicy.setHeightForWidth(self.label_57.sizePolicy().hasHeightForWidth())
        self.label_57.setSizePolicy(sizePolicy)
        self.label_58 = QLabel(self.centralwidget)
        self.label_58.setObjectName(u"label_58")
        self.label_58.setGeometry(QRect(518, 140, 31, 20))
        sizePolicy.setHeightForWidth(self.label_58.sizePolicy().hasHeightForWidth())
        self.label_58.setSizePolicy(sizePolicy)
        self.label_59 = QLabel(self.centralwidget)
        self.label_59.setObjectName(u"label_59")
        self.label_59.setGeometry(QRect(618, 260, 49, 16))
        sizePolicy.setHeightForWidth(self.label_59.sizePolicy().hasHeightForWidth())
        self.label_59.setSizePolicy(sizePolicy)
        self.label_60 = QLabel(self.centralwidget)
        self.label_60.setObjectName(u"label_60")
        self.label_60.setGeometry(QRect(618, 180, 49, 16))
        sizePolicy.setHeightForWidth(self.label_60.sizePolicy().hasHeightForWidth())
        self.label_60.setSizePolicy(sizePolicy)
        self.label_61 = QLabel(self.centralwidget)
        self.label_61.setObjectName(u"label_61")
        self.label_61.setGeometry(QRect(518, 120, 31, 20))
        sizePolicy.setHeightForWidth(self.label_61.sizePolicy().hasHeightForWidth())
        self.label_61.setSizePolicy(sizePolicy)
        self.label_62 = QLabel(self.centralwidget)
        self.label_62.setObjectName(u"label_62")
        self.label_62.setGeometry(QRect(618, 300, 49, 16))
        sizePolicy.setHeightForWidth(self.label_62.sizePolicy().hasHeightForWidth())
        self.label_62.setSizePolicy(sizePolicy)
        self.label_63 = QLabel(self.centralwidget)
        self.label_63.setObjectName(u"label_63")
        self.label_63.setGeometry(QRect(618, 240, 49, 16))
        sizePolicy.setHeightForWidth(self.label_63.sizePolicy().hasHeightForWidth())
        self.label_63.setSizePolicy(sizePolicy)
        self.label_64 = QLabel(self.centralwidget)
        self.label_64.setObjectName(u"label_64")
        self.label_64.setGeometry(QRect(518, 200, 31, 20))
        sizePolicy.setHeightForWidth(self.label_64.sizePolicy().hasHeightForWidth())
        self.label_64.setSizePolicy(sizePolicy)
        self.label_65 = QLabel(self.centralwidget)
        self.label_65.setObjectName(u"label_65")
        self.label_65.setGeometry(QRect(518, 320, 31, 20))
        sizePolicy.setHeightForWidth(self.label_65.sizePolicy().hasHeightForWidth())
        self.label_65.setSizePolicy(sizePolicy)
        self.label_66 = QLabel(self.centralwidget)
        self.label_66.setObjectName(u"label_66")
        self.label_66.setGeometry(QRect(518, 260, 31, 20))
        sizePolicy.setHeightForWidth(self.label_66.sizePolicy().hasHeightForWidth())
        self.label_66.setSizePolicy(sizePolicy)
        self.label_67 = QLabel(self.centralwidget)
        self.label_67.setObjectName(u"label_67")
        self.label_67.setGeometry(QRect(518, 180, 31, 20))
        sizePolicy.setHeightForWidth(self.label_67.sizePolicy().hasHeightForWidth())
        self.label_67.setSizePolicy(sizePolicy)
        self.label_68 = QLabel(self.centralwidget)
        self.label_68.setObjectName(u"label_68")
        self.label_68.setGeometry(QRect(618, 120, 49, 16))
        sizePolicy.setHeightForWidth(self.label_68.sizePolicy().hasHeightForWidth())
        self.label_68.setSizePolicy(sizePolicy)
        self.jPText = QLineEdit(self.centralwidget)
        self.jPText.setObjectName(u"jPText")
        self.jPText.setGeometry(QRect(550, 200, 61, 21))
        sizePolicy1.setHeightForWidth(self.jPText.sizePolicy().hasHeightForWidth())
        self.jPText.setSizePolicy(sizePolicy1)
        self.jPText.setReadOnly(True)
        self.label_69 = QLabel(self.centralwidget)
        self.label_69.setObjectName(u"label_69")
        self.label_69.setGeometry(QRect(618, 160, 49, 16))
        sizePolicy.setHeightForWidth(self.label_69.sizePolicy().hasHeightForWidth())
        self.label_69.setSizePolicy(sizePolicy)
        self.sXText = QLineEdit(self.centralwidget)
        self.sXText.setObjectName(u"sXText")
        self.sXText.setGeometry(QRect(550, 80, 61, 21))
        sizePolicy1.setHeightForWidth(self.sXText.sizePolicy().hasHeightForWidth())
        self.sXText.setSizePolicy(sizePolicy1)
        self.sXText.setReadOnly(True)
        self.label_70 = QLabel(self.centralwidget)
        self.label_70.setObjectName(u"label_70")
        self.label_70.setGeometry(QRect(618, 140, 49, 16))
        sizePolicy.setHeightForWidth(self.label_70.sizePolicy().hasHeightForWidth())
        self.label_70.setSizePolicy(sizePolicy)
        self.wXText = QLineEdit(self.centralwidget)
        self.wXText.setObjectName(u"wXText")
        self.wXText.setGeometry(QRect(550, 220, 61, 21))
        sizePolicy1.setHeightForWidth(self.wXText.sizePolicy().hasHeightForWidth())
        self.wXText.setSizePolicy(sizePolicy1)
        self.wXText.setReadOnly(True)
        self.iYText = QLineEdit(self.centralwidget)
        self.iYText.setObjectName(u"iYText")
        self.iYText.setGeometry(QRect(550, 280, 61, 21))
        sizePolicy1.setHeightForWidth(self.iYText.sizePolicy().hasHeightForWidth())
        self.iYText.setSizePolicy(sizePolicy1)
        self.iYText.setReadOnly(True)
        self.label_71 = QLabel(self.centralwidget)
        self.label_71.setObjectName(u"label_71")
        self.label_71.setGeometry(QRect(518, 220, 31, 20))
        sizePolicy.setHeightForWidth(self.label_71.sizePolicy().hasHeightForWidth())
        self.label_71.setSizePolicy(sizePolicy)
        self.label_72 = QLabel(self.centralwidget)
        self.label_72.setObjectName(u"label_72")
        self.label_72.setGeometry(QRect(618, 40, 49, 16))
        sizePolicy.setHeightForWidth(self.label_72.sizePolicy().hasHeightForWidth())
        self.label_72.setSizePolicy(sizePolicy)
        self.yCText = QLineEdit(self.centralwidget)
        self.yCText.setObjectName(u"yCText")
        self.yCText.setGeometry(QRect(550, 140, 61, 21))
        sizePolicy1.setHeightForWidth(self.yCText.sizePolicy().hasHeightForWidth())
        self.yCText.setSizePolicy(sizePolicy1)
        self.yCText.setReadOnly(True)
        self.wYText = QLineEdit(self.centralwidget)
        self.wYText.setObjectName(u"wYText")
        self.wYText.setGeometry(QRect(550, 240, 61, 21))
        sizePolicy1.setHeightForWidth(self.wYText.sizePolicy().hasHeightForWidth())
        self.wYText.setSizePolicy(sizePolicy1)
        self.wYText.setReadOnly(True)
        self.label_73 = QLabel(self.centralwidget)
        self.label_73.setObjectName(u"label_73")
        self.label_73.setGeometry(QRect(618, 220, 49, 16))
        sizePolicy.setHeightForWidth(self.label_73.sizePolicy().hasHeightForWidth())
        self.label_73.setSizePolicy(sizePolicy)
        self.label_74 = QLabel(self.centralwidget)
        self.label_74.setObjectName(u"label_74")
        self.label_74.setGeometry(QRect(518, 80, 31, 20))
        sizePolicy.setHeightForWidth(self.label_74.sizePolicy().hasHeightForWidth())
        self.label_74.setSizePolicy(sizePolicy)
        self.bText = QLineEdit(self.centralwidget)
        self.bText.setObjectName(u"bText")
        self.bText.setGeometry(QRect(550, 320, 61, 21))
        sizePolicy1.setHeightForWidth(self.bText.sizePolicy().hasHeightForWidth())
        self.bText.setSizePolicy(sizePolicy1)
        self.bText.setReadOnly(True)
        self.label_75 = QLabel(self.centralwidget)
        self.label_75.setObjectName(u"label_75")
        self.label_75.setGeometry(QRect(518, 60, 31, 20))
        sizePolicy.setHeightForWidth(self.label_75.sizePolicy().hasHeightForWidth())
        self.label_75.setSizePolicy(sizePolicy)
        self.sYText = QLineEdit(self.centralwidget)
        self.sYText.setObjectName(u"sYText")
        self.sYText.setGeometry(QRect(550, 100, 61, 21))
        sizePolicy1.setHeightForWidth(self.sYText.sizePolicy().hasHeightForWidth())
        self.sYText.setSizePolicy(sizePolicy1)
        self.sYText.setReadOnly(True)
        self.hText = QLineEdit(self.centralwidget)
        self.hText.setObjectName(u"hText")
        self.hText.setGeometry(QRect(550, 300, 61, 21))
        sizePolicy1.setHeightForWidth(self.hText.sizePolicy().hasHeightForWidth())
        self.hText.setSizePolicy(sizePolicy1)
        self.hText.setReadOnly(True)
        self.label_76 = QLabel(self.centralwidget)
        self.label_76.setObjectName(u"label_76")
        self.label_76.setGeometry(QRect(618, 60, 49, 16))
        sizePolicy.setHeightForWidth(self.label_76.sizePolicy().hasHeightForWidth())
        self.label_76.setSizePolicy(sizePolicy)
        self.jYText = QLineEdit(self.centralwidget)
        self.jYText.setObjectName(u"jYText")
        self.jYText.setGeometry(QRect(550, 180, 61, 21))
        sizePolicy1.setHeightForWidth(self.jYText.sizePolicy().hasHeightForWidth())
        self.jYText.setSizePolicy(sizePolicy1)
        self.jYText.setReadOnly(True)
        self.iXText = QLineEdit(self.centralwidget)
        self.iXText.setObjectName(u"iXText")
        self.iXText.setGeometry(QRect(550, 260, 61, 21))
        sizePolicy1.setHeightForWidth(self.iXText.sizePolicy().hasHeightForWidth())
        self.iXText.setSizePolicy(sizePolicy1)
        self.iXText.setReadOnly(True)
        self.picLabel = QLabel(self.centralwidget)
        self.picLabel.setObjectName(u"picLabel")
        self.picLabel.setGeometry(QRect(160, 20, 351, 381))
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)
        QWidget.setTabOrder(self.tText, self.lStText)
        QWidget.setTabOrder(self.lStText, self.lOtTex)
        QWidget.setTabOrder(self.lOtTex, self.rVnText)
        QWidget.setTabOrder(self.rVnText, self.solveBtn)
        QWidget.setTabOrder(self.solveBtn, self.rOsText)
        QWidget.setTabOrder(self.rOsText, self.bText)
        QWidget.setTabOrder(self.bText, self.aText)
        QWidget.setTabOrder(self.aText, self.sXText)
        QWidget.setTabOrder(self.sXText, self.sYText)
        QWidget.setTabOrder(self.sYText, self.xCText)
        QWidget.setTabOrder(self.xCText, self.yCText)
        QWidget.setTabOrder(self.yCText, self.jXText)
        QWidget.setTabOrder(self.jXText, self.jYText)
        QWidget.setTabOrder(self.jYText, self.jPText)
        QWidget.setTabOrder(self.jPText, self.wXText)
        QWidget.setTabOrder(self.wXText, self.wYText)
        QWidget.setTabOrder(self.wYText, self.iYText)
        QWidget.setTabOrder(self.iYText, self.iXText)
        QWidget.setTabOrder(self.iXText, self.hText)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"\u0413\u0435\u043e\u043c\u0435\u0442\u0440\u0438\u0447\u0435\u0441\u043a\u0438\u0435 \u0445\u0430\u0440\u0430\u043a\u0442\u0435\u0440\u0438\u0441\u0442\u0438\u043a\u0438 V-\u043e\u0431\u0440\u0430\u0437\u043d\u043e\u0433\u043e \u0441\u0435\u0447\u0435\u043d\u0438\u044f", None))
        self.solveBtn.setText(QCoreApplication.translate("MainWindow", u"\u0420\u0435\u0448\u0438\u0442\u044c", None))
        self.label_39.setText(QCoreApplication.translate("MainWindow", u"\u043c\u043c", None))
        self.label_40.setText(QCoreApplication.translate("MainWindow", u"t =", None))
        self.label_41.setText(QCoreApplication.translate("MainWindow", u"\u043c\u043c", None))
        self.label_42.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p>L<span style=\" vertical-align:sub;\">\u043e\u0442</span> =</p></body></html>", None))
        self.label_43.setText(QCoreApplication.translate("MainWindow", u"R<sub>\u0432\u043d</sub> =", None))
        self.label_44.setText(QCoreApplication.translate("MainWindow", u"L<sub>\u0441\u0442<sub/>", None))
        self.label_45.setText(QCoreApplication.translate("MainWindow", u"\u043c\u043c", None))
        self.label_46.setText(QCoreApplication.translate("MainWindow", u"\u043c\u043c", None))
        self.label_47.setText(QCoreApplication.translate("MainWindow", u"W<sub>y</sub> =", None))
        self.label_48.setText(QCoreApplication.translate("MainWindow", u"\u0441\u043c<sup>3</sup>", None))
        self.label_49.setText(QCoreApplication.translate("MainWindow", u"\u0441\u043c", None))
        self.label_50.setText(QCoreApplication.translate("MainWindow", u"S<sub>y</sub> =", None))
        self.label_51.setText(QCoreApplication.translate("MainWindow", u"\u0441\u043c<sup>4</sup>", None))
        self.label_52.setText(QCoreApplication.translate("MainWindow", u"J<sub>x</sub> =", None))
        self.label_53.setText(QCoreApplication.translate("MainWindow", u"\u043c\u043c", None))
        self.label_54.setText(QCoreApplication.translate("MainWindow", u"i<sub>y</sub> =", None))
        self.label_55.setText(QCoreApplication.translate("MainWindow", u"R<sub>\u043e\u0441 =", None))
        self.label_56.setText(QCoreApplication.translate("MainWindow", u"\u0441\u043c<sup>3</sup>", None))
        self.label_57.setText(QCoreApplication.translate("MainWindow", u"H =", None))
        self.label_58.setText(QCoreApplication.translate("MainWindow", u"y<sub>c</sub> =", None))
        self.label_59.setText(QCoreApplication.translate("MainWindow", u"\u0441\u043c", None))
        self.label_60.setText(QCoreApplication.translate("MainWindow", u"\u0441\u043c<sup>4</sup>", None))
        self.label_61.setText(QCoreApplication.translate("MainWindow", u"x<sub>c</sub> =", None))
        self.label_62.setText(QCoreApplication.translate("MainWindow", u"\u043c\u043c", None))
        self.label_63.setText(QCoreApplication.translate("MainWindow", u"\u0441\u043c<sup>3</sup>", None))
        self.label_64.setText(QCoreApplication.translate("MainWindow", u"J<sub>p</sub> =", None))
        self.label_65.setText(QCoreApplication.translate("MainWindow", u"B =", None))
        self.label_66.setText(QCoreApplication.translate("MainWindow", u"i<sub>x</sub> =", None))
        self.label_67.setText(QCoreApplication.translate("MainWindow", u"J<sub>y</sub> =", None))
        self.label_68.setText(QCoreApplication.translate("MainWindow", u"\u0441\u043c", None))
        self.label_69.setText(QCoreApplication.translate("MainWindow", u"\u0441\u043c<sup>4</sup>", None))
        self.label_70.setText(QCoreApplication.translate("MainWindow", u"\u0441\u043c", None))
        self.label_71.setText(QCoreApplication.translate("MainWindow", u"W<sub>x</sub> =", None))
        self.label_72.setText(QCoreApplication.translate("MainWindow", u"\u043c\u043c", None))
        self.label_73.setText(QCoreApplication.translate("MainWindow", u"\u0441\u043c<sup>3</sup>", None))
        self.label_74.setText(QCoreApplication.translate("MainWindow", u"S<sub>x</sub> =", None))
        self.label_75.setText(QCoreApplication.translate("MainWindow", u"A =", None))
        self.label_76.setText(QCoreApplication.translate("MainWindow", u"\u0441\u043c<sup>2</sup>", None))
        self.picLabel.setText("")
    # retranslateUi

